### PR TITLE
add mips and mipsel dependencies

### PR DESCRIPTION
**Pull request by psych0d0g**
#8

### CODE REVIEW

**Comment by conradkleinespel** [comment]
Thanks for the PR @psych0d0g. The Windows build seems to be broken. I'll check why and get back to you shortly.

**Comment by conradkleinespel** [comment]
Looking good.

Would you know of a way to add automated builds for the `mips` and `mipsel` platforms ?

**Comment by conradkleinespel** [comment]
I will push a new version of the library to crates.io in a few seconds so you can install it via `cargo`.

**Comment by psych0d0g** [comment]
i dont know how travisci handles mips and mipsel builds but for rust you would need the stdlib for mips and mipsel from http://static.rust-lang.org/dist/rust-std-nightly-mipsel-unknown-linux-gnu.tar.gz and http://static.rust-lang.org/dist/rust-std-nightly-mips-unknown-linux-gnu.tar.gz.
also you would need the gcc crosscompiler toolchains for those 2 architectures

**Comment by conradkleinespel** [comment]
Alright, thanks for the explanation. I'll try to set this up someday if I find the time.

**Pull request merged**
