### PR TITLE
Fix ARMv7 target

### PR DESCRIPTION
**Pull request by petevine**

### CODE REVIEW

**Comment by conradkleinespel** [comment]
Hello @petevine, thanks for submitting this patch ! I will push this to crates.io in a few minutes.

**Comment by petevine** [comment]
Thx! I wonder how many of those are still left in the wild.

@japaric Is crater capable of detecting them?

**Comment by conradkleinespel** [comment]
@petevine I don't know, to be frank. But with Rust 1.8 being out, I'm just waiting to have the new packages on my laptop and then all of this dependency description mess can go away, as we'll have stuff like `[dependencies.'cfg(windows)']` and `[dependencies.'cfg(not(windows))']`.

So to answer your question, Cargo can handle all of that as of Rust 1.8, I think.

**Comment by conradkleinespel** [comment]
@petevine I've pushed this to crates.io as `v0.2.1`. Also, I've added you to the contributor list (please say if you do not wish to appear in it, I tend to add contributors as they deserve the credit). Thanks again for your help.

**Comment by petevine** [comment]
@conradkleinespel No prob, thanks.

**Comment by japaric** [comment]
> @japaric Is crater capable of detecting them?

I don't know. I haven't really looked at crater or its output before. But I suppose it builds crates with `--target=$host` (i.e. the default) where host is probably `x86_64-unknown-linux-gnu`. Running crater with `--target=x86_64-unknown-linux-gnu` and then with `--target=armv7-unknown-linux-gnueabihf` (or any other target) to check the regressions between the two runs would be an interesting experiment though! (cc @brson) I expect it would catch issues like this one and it general would tell us which crates are cross compilable or not.

**Comment by brson** [comment]
Crater can't currently do cross-compiles. It only builds for x86_64-unknown-linux-gnu.

**Pull request merged**
